// Simulated admin credentials (in a real app, use secure authentication methods)
const adminUsername = "admin";
const adminPassword = "password";

// Admin login functionality
document.getElementById("adminBtn").addEventListener("click", function() {
    const input = prompt("Enter admin username and password separated by comma (username,password):");
    if (input) {
        const [username, password] = input.split(",");
        if (username.trim() === adminUsername && password.trim() === adminPassword) {
            document.getElementById("attendancePanel").style.display = "none";
            document.getElementById("adminPanel").style.display = "block";
        } else {
            alert("Invalid credentials. Access denied.");
        }
    }
});

// Logout functionality
document.getElementById("logoutBtn").addEventListener("click", function() {
    document.getElementById("attendancePanel").style.display = "block";
    document.getElementById("adminPanel").style.display = "none";
});

// Attendance marking functionality
document.getElementById("attendanceForm").addEventListener("submit", function(event) {
    event.preventDefault();
    const employeeId = document.getElementById("employeeId").value.trim();
    if (employeeId === "") {
        displayMessage("Please enter employee ID.", "error");
    } else {
        // Here you can implement logic to mark attendance (e.g., store in localStorage or send to server)
        displayMessage(`Attendance marked for employee ID: ${employeeId}`, "success");
        document.getElementById("employeeId").value = "";
    }
});

// Display message function
function displayMessage(message, messageType) {
    const messageDiv = document.getElementById("attendanceMessage");
    messageDiv.textContent = message;
    messageDiv.className = messageType;
    setTimeout(function() {
        messageDiv.textContent = "";
        messageDiv.className = "";
    }, 3000);
}

// Admin controls
document.getElementById("viewAttendanceBtn").addEventListener("click", function() {
    // Simulated action to view attendance
    alert("Viewing attendance...");
    console.log("Admin viewed attendance");
});

document.getElementById("generateReportBtn").addEventListener("click", function() {
    // Simulated action to generate report
    generateReport();
});

// Function to generate report (simulated)
function generateReport() {
    const reportContainer = document.getElementById("reportContainer");
    reportContainer.innerHTML = `
        <h2>Attendance Report</h2>
        <p>Date: ${new Date().toLocaleDateString()}</p>
        <p>Generated by: Admin</p>
        <table>
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>Name</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>12345</td>
                    <td>John Doe</td>
                    <td>Present</td>
                </tr>
                <tr>
                    <td>67890</td>
                    <td>Jane Smith</td>
                    <td>Absent</td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>
    `;
}
